CC=g++
CFLAGS= -W -std=gnu++11 
AUTOGENJSONDIR= autoGeneratedJsonClasses

LIBS=-lssl -lcrypto -lcurl
DEPS= jsonRetriverInterface.h jsonRetriver.h searchCondition.h $(AUTOGENJSONDIR)/Listings.h $(AUTOGENJSONDIR)/Address.h $(AUTOGENJSONDIR)/Areas.h $(AUTOGENJSONDIR)/Distance.h $(AUTOGENJSONDIR)/Location.h $(AUTOGENJSONDIR)/Position.h $(AUTOGENJSONDIR)/Region.h $(AUTOGENJSONDIR)/Result.h $(AUTOGENJSONDIR)/SearchParams.h $(AUTOGENJSONDIR)/Sold.h $(AUTOGENJSONDIR)/Source.h curlException.h Booli.h BooliFactory.h

OBJ= jsonRetriver.o searchCondition.o $(AUTOGENJSONDIR)/Listings.o $(AUTOGENJSONDIR)/Address.o $(AUTOGENJSONDIR)/Areas.o $(AUTOGENJSONDIR)/Distance.o $(AUTOGENJSONDIR)/Location.o $(AUTOGENJSONDIR)/Position.o $(AUTOGENJSONDIR)/Region.o $(AUTOGENJSONDIR)/Result.o $(AUTOGENJSONDIR)/SearchParams.o $(AUTOGENJSONDIR)/Sold.o $(AUTOGENJSONDIR)/Source.o Booli.o BooliFactory.o

%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)  

boolilibrary : $(OBJ)
	ar rvs booli.a $(OBJ)

boolitest : main.cpp booli.a
	$(CC) -o $@ $(CFLAGS) main.cpp booli.a $(LIBS)

unittest : unitTests.cpp jsonRetriverFake.cpp booli.a
	$(CC) -o $@ $(CFLAGS) unitTests.cpp jsonRetriverFake.cpp booli.a $(LIBS) -lgtest -lpthread

clean :
	rm -f *.o *~ *.a boolitest unittest
